size(200);
pair P = (0, 10);
pair Q = (0, 0);
pair R = (10, 0);
pair S = (10, 10);
pair T = (14, 0);
pair U = (10, 2.85714);
draw(P--Q);
draw(Q--R);
draw(R--S);
draw(S--P);
draw(R--T);
draw(P--T);
draw(P--R);
label("$P$", P, NW);
label("$Q$", Q, SW);
label("$R$", R, S);
label("$S$", S, NE);
label("$T$", T, E);
label("$U$", U, NE);
// Right angle at Q
pair vec1 = unit(P - Q);
pair vec2 = unit(R - Q);
pair pt1 = Q + 0.5*vec1;
pair pt2 = Q + 0.5*vec2;
pair corner = Q + 0.5*vec1 + 0.5*vec2;
draw(pt1--corner--pt2);
// Right angle at R
pair vec1 = unit(Q - R);
pair vec2 = unit(S - R);
pair pt1 = R + 0.5*vec1;
pair pt2 = R + 0.5*vec2;
pair corner = R + 0.5*vec1 + 0.5*vec2;
draw(pt1--corner--pt2);
pair mid_R_T = (R + T) / 2.0;
label("2.1", mid_R_T, S);
pair mid_U_T = (U + T) / 2.0;
label("2.9", mid_U_T, NE);